//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class guanwang_title
    {
        public int titleID { get; set; }
        public string title1 { get; set; }
        public string describe1 { get; set; }
        public string title2 { get; set; }
        public string describe2 { get; set; }
        public string title3 { get; set; }
        public string describe3 { get; set; }
        public string title4 { get; set; }
        public string describe4 { get; set; }
        public string title5 { get; set; }
        public string describe5 { get; set; }
        public string title6 { get; set; }
        public string describe6 { get; set; }
        public Nullable<int> typeid { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
    }
}
