//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class guanwang_vyw_case_type
    {
        public int caseID { get; set; }
        public string describe { get; set; }
        public string image { get; set; }
        public Nullable<int> typeID { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public Nullable<int> userID { get; set; }
        public string userName { get; set; }
        public string userEmail { get; set; }
        public int userRole { get; set; }
        public bool userStatus { get; set; }
        public string realName { get; set; }
        public string position { get; set; }
        public string userTags { get; set; }
        public string userDescribe { get; set; }
        public string userWeb { get; set; }
        public string facebook { get; set; }
        public string userImage { get; set; }
        public string twitter { get; set; }
        public string googlePlus { get; set; }
        public string address { get; set; }
        public string area { get; set; }
        public string phone { get; set; }
        public string link { get; set; }
        public Nullable<int> weight { get; set; }
    }
}
