//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class guanwang_pricing
    {
        public int pricingID { get; set; }
        public string title { get; set; }
        public string price { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string url { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
    }
}
