//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qds11527190_dbEntities : DbContext
    {
        public qds11527190_dbEntities()
            : base("name=qds11527190_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<guanwang_banner_about> guanwang_banner_about { get; set; }
        public DbSet<guanwang_banner_index> guanwang_banner_index { get; set; }
        public DbSet<guanwang_blog> guanwang_blog { get; set; }
        public DbSet<guanwang_blog_type> guanwang_blog_type { get; set; }
        public DbSet<guanwang_case> guanwang_case { get; set; }
        public DbSet<guanwang_case_type> guanwang_case_type { get; set; }
        public DbSet<guanwang_evaluation> guanwang_evaluation { get; set; }
        public DbSet<guanwang_feedback> guanwang_feedback { get; set; }
        public DbSet<guanwang_footer> guanwang_footer { get; set; }
        public DbSet<guanwang_good> guanwang_good { get; set; }
        public DbSet<guanwang_hot> guanwang_hot { get; set; }
        public DbSet<guanwang_like> guanwang_like { get; set; }
        public DbSet<guanwang_partner> guanwang_partner { get; set; }
        public DbSet<guanwang_pricing> guanwang_pricing { get; set; }
        public DbSet<guanwang_product> guanwang_product { get; set; }
        public DbSet<guanwang_product_type> guanwang_product_type { get; set; }
        public DbSet<guanwang_service> guanwang_service { get; set; }
        public DbSet<guanwang_skill> guanwang_skill { get; set; }
        public DbSet<guanwang_template> guanwang_template { get; set; }
        public DbSet<guanwang_template_title> guanwang_template_title { get; set; }
        public DbSet<guanwang_title> guanwang_title { get; set; }
        public DbSet<guanwang_user> guanwang_user { get; set; }
        public DbSet<guanwang_web> guanwang_web { get; set; }
        public DbSet<guanwang_web_type> guanwang_web_type { get; set; }
        public DbSet<guanwang_website> guanwang_website { get; set; }
        public DbSet<guanwang_vyw_blog_type_user> guanwang_vyw_blog_type_user { get; set; }
        public DbSet<guanwang_vyw_case_type> guanwang_vyw_case_type { get; set; }
        public DbSet<guanwang_vyw_product_type> guanwang_vyw_product_type { get; set; }
        public DbSet<guanwang_vyw_template_title> guanwang_vyw_template_title { get; set; }
        public DbSet<guanwang_vyw_web_type> guanwang_vyw_web_type { get; set; }
    }
}
